"""Tool name → AgentService handler mapping (kept out of agent_service for readability)."""

from __future__ import annotations

# name → (handler method name on AgentService, takes_run_id)
AGENT_TOOL_DISPATCH: dict[str, tuple[str, bool]] = {
    "gmail_list_messages": ("_tool_gmail_list_messages", False),
    "gmail_get_message": ("_tool_gmail_get_message", False),
    "gmail_get_thread": ("_tool_gmail_get_thread", False),
    "gmail_list_labels": ("_tool_gmail_list_labels", False),
    "gmail_list_filters": ("_tool_gmail_list_filters", False),
    "calendar_list_events": ("_tool_calendar_list_events", False),
    "drive_list_files": ("_tool_drive_list_files", False),
    "outlook_list_messages": ("_tool_outlook_list_messages", False),
    "outlook_get_message": ("_tool_outlook_get_message", False),
    "teams_list_teams": ("_tool_teams_list_teams", False),
    "teams_list_channels": ("_tool_teams_list_channels", False),
    "list_connectors": ("_tool_list_connectors", False),
    "get_session_time": ("_tool_get_session_time", False),
    "gmail_modify_message": ("_tool_gmail_modify_message", False),
    "gmail_modify_thread": ("_tool_gmail_modify_thread", False),
    "gmail_trash_message": ("_tool_gmail_trash_message", False),
    "gmail_untrash_message": ("_tool_gmail_untrash_message", False),
    "gmail_trash_thread": ("_tool_gmail_trash_thread", False),
    "gmail_trash_bulk_query": ("_tool_gmail_trash_bulk_query", False),
    "gmail_untrash_thread": ("_tool_gmail_untrash_thread", False),
    "gmail_mark_read": ("_tool_gmail_mark_read", False),
    "gmail_mark_unread": ("_tool_gmail_mark_unread", False),
    "gmail_silence_sender": ("_tool_gmail_silence_sender", False),
    "gmail_create_filter": ("_tool_gmail_create_filter", False),
    "gmail_delete_filter": ("_tool_gmail_delete_filter", False),
    "calendar_create_event": ("_tool_calendar_create_event", False),
    "calendar_update_event": ("_tool_calendar_update_event", False),
    "calendar_delete_event": ("_tool_calendar_delete_event", False),
    "drive_upload_file": ("_tool_drive_upload_file", False),
    "drive_share_file": ("_tool_drive_share_file", False),
    "teams_post_message": ("_tool_teams_post_message", False),
    "upsert_memory": ("_tool_upsert_memory", False),
    "delete_memory": ("_tool_delete_memory", False),
    "list_memory": ("_tool_list_memory", False),
    "recall_memory": ("_tool_recall_memory", False),
    "list_skills": ("_tool_list_skills", False),
    "load_skill": ("_tool_load_skill", False),
    "list_workspace_files": ("_tool_list_workspace_files", False),
    "read_workspace_file": ("_tool_read_workspace_file", False),
    "describe_harness": ("_tool_describe_harness", False),
    "start_connector_setup": ("_tool_start_connector_setup", False),
    "submit_connector_credentials": ("_tool_submit_connector_credentials", False),
    "start_oauth_flow": ("_tool_start_oauth_flow", False),
    "propose_email_send": ("_tool_propose_email_send", True),
    "propose_email_reply": ("_tool_propose_email_reply", True),
}
