"""Agent tool dispatch table."""
from app.services.agent.handlers import (
    gmail, calendar, drive, sheets_docs, tasks, people,
    social, third_party, icloud, memory, skills, proposal,
    scheduled, misc, loop_core,
)

AGENT_TOOL_DISPATCH = {
    "_tool_gmail_list_messages": gmail._tool_gmail_list_messages,
    "_tool_gmail_get_message": gmail._tool_gmail_get_message,
    "_tool_gmail_get_thread": gmail._tool_gmail_get_thread,
    "_tool_gmail_list_labels": gmail._tool_gmail_list_labels,
    "_tool_gmail_list_filters": gmail._tool_gmail_list_filters,
    "_tool_gmail_modify_message": gmail._tool_gmail_modify_message,
    "_tool_gmail_modify_thread": gmail._tool_gmail_modify_thread,
    "_tool_gmail_trash_message": gmail._tool_gmail_trash_message,
    "_tool_gmail_untrash_message": gmail._tool_gmail_untrash_message,
    "_tool_gmail_trash_thread": gmail._tool_gmail_trash_thread,
    "_tool_gmail_untrash_thread": gmail._tool_gmail_untrash_thread,
    "_tool_gmail_trash_bulk_query": gmail._tool_gmail_trash_bulk_query,
    "_tool_gmail_mark_read": gmail._tool_gmail_mark_read,
    "_tool_gmail_mark_unread": gmail._tool_gmail_mark_unread,
    "_tool_gmail_silence_sender": gmail._tool_gmail_silence_sender,
    "_tool_gmail_create_filter": gmail._tool_gmail_create_filter,
    "_tool_gmail_delete_filter": gmail._tool_gmail_delete_filter,
    "_tool_calendar_list_calendars": calendar._tool_calendar_list_calendars,
    "_tool_calendar_list_events": calendar._tool_calendar_list_events,
    "_tool_calendar_create_event": calendar._tool_calendar_create_event,
    "_tool_calendar_update_event": calendar._tool_calendar_update_event,
    "_tool_calendar_delete_event": calendar._tool_calendar_delete_event,
    "_tool_drive_list_files": drive._tool_drive_list_files,
    "_tool_drive_upload_file": drive._tool_drive_upload_file,
    "_tool_sheets_read_range": sheets_docs._tool_sheets_read_range,
    "_tool_docs_get_document": sheets_docs._tool_docs_get_document,
    "_tool_tasks_list_tasklists": tasks._tool_tasks_list_tasklists,
    "_tool_tasks_list_tasks": tasks._tool_tasks_list_tasks,
    "_tool_tasks_create_task": tasks._tool_tasks_create_task,
    "_tool_tasks_update_task": tasks._tool_tasks_update_task,
    "_tool_tasks_delete_task": tasks._tool_tasks_delete_task,
    "_tool_people_search_contacts": people._tool_people_search_contacts,
    "_tool_slack_list_conversations": social._tool_slack_list_conversations,
    "_tool_slack_get_conversation_history": social._tool_slack_get_conversation_history,
    "_tool_telegram_get_me": social._tool_telegram_get_me,
    "_tool_telegram_get_updates": social._tool_telegram_get_updates,
    "_tool_telegram_send_message": social._tool_telegram_send_message,
    "_tool_outlook_list_messages": social._tool_outlook_list_messages,
    "_tool_outlook_get_message": social._tool_outlook_get_message,
    "_tool_github_list_my_repos": third_party._tool_github_list_my_repos,
    "_tool_github_list_repo_issues": third_party._tool_github_list_repo_issues,
    "_tool_linear_list_issues": third_party._tool_linear_list_issues,
    "_tool_linear_get_issue": third_party._tool_linear_get_issue,
    "_tool_notion_search": third_party._tool_notion_search,
    "_tool_notion_get_page": third_party._tool_notion_get_page,
    "_tool_upsert_memory": memory._tool_upsert_memory,
    "_tool_delete_memory": memory._tool_delete_memory,
    "_tool_list_memory": memory._tool_list_memory,
    "_tool_recall_memory": memory._tool_recall_memory,
    "_tool_memory_get": memory._tool_memory_get,
    "_tool_list_skills": skills._tool_list_skills,
    "_tool_load_skill": skills._tool_load_skill,
    "_tool_list_workspace_files": skills._tool_list_workspace_files,
    "_tool_read_workspace_file": skills._tool_read_workspace_file,
    "_tool_propose_email_send": proposal._tool_propose_email_send,
    "_tool_propose_email_reply": proposal._tool_propose_email_reply,
    "_tool_propose_whatsapp_send": proposal._tool_propose_whatsapp_send,
    "_tool_propose_slack_post_message": proposal._tool_propose_slack_post_message,
    "_tool_propose_linear_create_comment": proposal._tool_propose_linear_create_comment,
    "_tool_propose_telegram_send_message": proposal._tool_propose_telegram_send_message,
    "_tool_scheduled_task_create": scheduled._tool_scheduled_task_create,
    "_tool_scheduled_task_list": scheduled._tool_scheduled_task_list,
    "_tool_scheduled_task_update": scheduled._tool_scheduled_task_update,
    "_tool_scheduled_task_delete": scheduled._tool_scheduled_task_delete,
    "_scheduled_task_to_dict": misc._scheduled_task_to_dict,
    "_tool_device_list_ingested_files": misc._tool_device_list_ingested_files,
    "_tool_device_get_ingested_file": misc._tool_device_get_ingested_file,
    "_tool_list_connectors": misc._tool_list_connectors,
    "_tool_get_session_time": misc._tool_get_session_time,
    "_tool_web_search": misc._tool_web_search,
    "_tool_web_fetch": misc._tool_web_fetch,
    "_tool_start_connector_setup": misc._tool_start_connector_setup,
    "_tool_submit_connector_credentials": misc._tool_submit_connector_credentials,
    "_tool_start_oauth_flow": misc._tool_start_oauth_flow,
    "_idem": misc._idem,
    "_parse_label_ids": loop_core._parse_label_ids,
    "_insert_proposal": loop_core._insert_proposal,
    "_dispatch_tool": loop_core._dispatch_tool,
    "run_agent_invalid_preflight": loop_core.run_agent_invalid_preflight,
    "abort_pending_run_queue_unavailable": loop_core.abort_pending_run_queue_unavailable,
    "create_pending_agent_run": loop_core.create_pending_agent_run,
    "run_agent": loop_core.run_agent,
    "_execute_agent_loop": loop_core._execute_agent_loop,
    "_load_steps": loop_core._load_steps,
    "_to_read": loop_core._to_read,
    "list_recent_runs": loop_core.list_recent_runs,
    "list_trace_events": loop_core.list_trace_events,
    "get_run": loop_core.get_run,
}

MEMORY_TOOLS = ["_tool_upsert_memory"
AGENT_TOOL_NAMES = list(AGENT_TOOL_DISPATCH.keys())
